version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo "$CIRCLE_WORKFLOW_ID"

workflows:
  version: 2
  build:
    jobs:
      - build
      - save_hello_world_output
      - print_output_file:
          # without ordering jobs, workspace is not filled when attached and no errors if workspace is empty
          requires:
            - save_hello_world_output
      - failing_on_pupose
      - act_on_failer

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "write hello world to file"
          command: echo "hello world" > output.txt
      - persist_to_workspace:
          root: .  # current working dir
          paths:  # list of files to persist to workspace
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      # attach the files you persisted in the doing-things-job
      - attach_workspace:
          at: ./workspace  # relative path to our working directory
      - print_pipeline_id  # calling reusable command (code)
      - run:
          command: |
            cat ./workspace/output.txt

  failing_on_pupose:
    docker:
      - image: cimg/base:stable
    steps:
      - run: return 1  # returning somting other than 0

  act_on_failer:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "Hello Error!"
          when: on_fail
